sudo: required
services:
    - docker

before_install:
    - docker build -t mikehell68/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mikehell68/react-test npm test

after_success:
    - docker build -t mikehell68/multi-client ./client
    - docker build -t mikehell68/multi-nginx ./nginx
    - docker build -t mikehell68/multi-server ./server
    - docker build -t mikehell68/multi-worker ./worker

# login to docker CLI & push images above to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push mikehell68/multi-client
    - docker push mikehell68/multi-nginx
    - docker push mikehell68/multi-server
    - docker push mikehell68/multi-worker

deploy:
    provider: elasticbeastalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-335642122127
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY